name: Go Test

on:
  push:
    branches: [main]
    paths:
      - "lambda_go/**"
      - ".github/workflows/go-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "lambda_go/**"
      - ".github/workflows/go-test.yml"

jobs:
  go-test:
    name: Go ユニットテスト
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ap-northeast-1
    defaults:
      run:
        working-directory: lambda_go/items_handler
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: lambda_go/items_handler/go.mod
      - name: go mod download
        run: go mod download
      - name: go test
        run: go test -v ./...
